"""T1: per-host breakdown of prospective DFT validation.

Reads results/prospective_dft_results.json and emits a LaTeX
tabular block with:
  - host name
  - n_A / n_B
  - mean predicted Ef per bucket
  - mean DFT-corrected Ef per bucket
  - per-host hit rate (DFT Ef < +1 eV) within bucket A
  - per-host worst |error|

Output:
  paper/tables/per_host_breakdown.tex   — \input{}-able LaTeX
  results/prospective_per_host.json     — JSON for sanity
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "results" / "prospective_dft_results.json"
OUT_TEX = ROOT / "paper" / "tables" / "per_host_breakdown.tex"
OUT_JSON = ROOT / "results" / "prospective_per_host.json"


def main():
    rows = json.loads(RES.read_text())["rows"]
    print(f"loaded {len(rows)} candidates")

    # per-dopant offset
    dop_off = defaultdict(list)
    for r in rows:
        dop_off[r["dopant"]].append(r["dft_Ef_eV"] - r["model_pred_Ef_eV"])
    mean_off = {d: float(np.mean(v)) for d, v in dop_off.items()}

    by_host = defaultdict(list)
    for r in rows:
        rr = dict(r)
        rr["dft_Ef_corr_eV"] = r["dft_Ef_eV"] - mean_off[r["dopant"]]
        rr["err_corr"] = abs(rr["dft_Ef_corr_eV"] - r["model_pred_Ef_eV"])
        by_host[r["host"]].append(rr)

    out = []
    for host in sorted(by_host):
        items = by_host[host]
        a = [r for r in items if r["bucket"].startswith("A")]
        b = [r for r in items if r["bucket"].startswith("B")]
        a_hit = sum(1 for r in a if r["dft_Ef_corr_eV"] < 1.0)
        worst = max(items, key=lambda r: r["err_corr"])
        out.append({
            "host": host,
            "n_A": len(a),
            "n_B": len(b),
            "mean_pred_A": float(np.mean([r["model_pred_Ef_eV"] for r in a])) if a else None,
            "mean_dft_corr_A": float(np.mean([r["dft_Ef_corr_eV"] for r in a])) if a else None,
            "A_hit_below_1eV": a_hit,
            "worst_err_eV": float(worst["err_corr"]),
            "worst_dopant": worst["dopant"],
        })

    OUT_JSON.write_text(json.dumps(out, indent=2))
    print(f"wrote {OUT_JSON}")

    # LaTeX
    OUT_TEX.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% per-host breakdown of prospective DFT validation",
        "% generated by scripts/make_per_host_table.py",
        r"\begin{table}[h]",
        r"\centering",
        r"\caption{Per-host breakdown of \modelname's prospective DFT "
        r"validation, after per-dopant chemical-potential offset "
        r"correction. ``$n_A$/$n_B$'' is the count of SCF-converged "
        r"candidates in bucket A (low-$E_f$ confident) and bucket B "
        r"(high-$\sigma$ OOD). ``hit'' is the count in bucket A with "
        r"DFT-corrected $E_f^{\rm DFT,corr}<+1$\,eV. ``worst $|\mathrm{err}|$'' "
        r"reports the largest single-candidate residual on each host "
        r"(in eV, with the offending dopant in parentheses).}",
        r"\label{tab:per-host}",
        r"\begin{tabular}{lrrrrrl}",
        r"\toprule",
        r"Host & $n_A$ & $n_B$ & $\langle\mu_{\rm pred}\rangle_A$ & "
        r"$\langle E_f^{\rm DFT,corr}\rangle_A$ & A hit & "
        r"worst $|\mathrm{err}|$ \\",
        r"      &  &  & (eV) & (eV) & ($<\!1$\,eV) & (eV, dopant) \\",
        r"\midrule",
    ]
    for r in out:
        mp = f"{r['mean_pred_A']:+.2f}" if r["mean_pred_A"] is not None else "---"
        mc = f"{r['mean_dft_corr_A']:+.2f}" if r["mean_dft_corr_A"] is not None else "---"
        h = f"{r['A_hit_below_1eV']}/{r['n_A']}" if r["n_A"] > 0 else "---"
        w = f"{r['worst_err_eV']:.2f} ({r['worst_dopant']})"
        # LaTeX-safe host name (subscripts on stoichiometry)
        host_tex = (r["host"]
                    .replace("Bi2I6", "Bi$_2$I$_6$")
                    .replace("BiITe", "BiITe")
                    .replace("C2H2", "C$_2$H$_2$")
                    .replace("Hf2Te6", "Hf$_2$Te$_6$")
                    .replace("Mo2CO2", "Mo$_2$CO$_2$")
                    .replace("MoS2", "MoS$_2$")
                    .replace("MoSe2", "MoSe$_2$")
                    .replace("MoTe2", "MoTe$_2$")
                    .replace("NbS2", "NbS$_2$")
                    .replace("NbSe2", "NbSe$_2$")
                    .replace("NiSe2", "NiSe$_2$")
                    .replace("Pd2Se4", "Pd$_2$Se$_4$")
                    .replace("PtS2", "PtS$_2$")
                    .replace("PtSe2", "PtSe$_2$")
                    .replace("Sn2", "Sn$_2$")
                    .replace("SnS2", "SnS$_2$")
                    .replace("SnSe2", "SnSe$_2$")
                    .replace("TaS2", "TaS$_2$")
                    .replace("Ti2CO2", "Ti$_2$CO$_2$")
                    .replace("TiO2", "TiO$_2$")
                    .replace("TiS2", "TiS$_2$")
                    .replace("V2CO2", "V$_2$CO$_2$")
                    .replace("WTe2", "WTe$_2$")
                    .replace("ZrS2", "ZrS$_2$")
                    .replace("ZrSe2", "ZrSe$_2$")
                    .replace("Ge2", "Ge$_2$"))
        lines.append(
            f"  {host_tex:<20s} & {r['n_A']} & {r['n_B']} & {mp} & {mc} & {h} & {w} \\\\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    OUT_TEX.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
